reports/urls.py
from django.conf.urls.defaults import *
from wilp.reports.views import *


urlpatterns = patterns('',

  (r'^basic/$',basic),

)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
from wilp.home.views import *
from wilp.faculty.views import *
from wilp.programme.views import *
from wilp.company.views import *
from wilp.coordinator.views import *
from wilp.studbatch.views import *
from django.contrib.auth.views import logout
admin.autodiscover()

urlpatterns = patterns('',
    
    url(r'^$',home,name='home'),
    url(r'^page/$',page,name='page  '),
    url(r'^logout/$',logout,{'template_name':'logout.html'},name ='logout'),
    url(r'^login/$',login,name='login'),
    url(r'^profile/$',profile,name='profile'),
    url(r'^editprofile/$',editprofile,name='editprofile'),
    url(r'^settings/$',coord_settings,name = 'settings'),
    url(r'^imports/$',imports,name='imports'),
    url(r'^reports/$',reports,name='reports'),
    url(r'^chaining/', include('smart_selects.urls')),

    url(r'^admin/', include(admin.site.urls),name = 'admin'),
    
     (r'^static/(?P<path>.*)$','django.views.static.serve',
         {'document_root': 'c:/Users/Ednha/wilp/static'}),
    
    
)


urlpatterns+=patterns('',

  url(r'^addfaculty/$',addfaculty,name='addfaculty'),
  url(r'^viewfaculty/$',viewfacs,name='viewfacs')

)

urlpatterns+=patterns('',

  url(r'^get_progs/$',getprogs),
  url(r'^get_courses/$',getcourses),

)

urlpatterns+=patterns('',

  url(r'^companies/$',advcompanies,name='advcompanies'),

)


urlpatterns+=patterns('',

  url(r'^companycoord/$',company_coord,name='companycoord'),
  url(r'^viewcompanycoords',viewcomcoords,name='viewcomcoords')

)

urlpatterns+=patterns('',

  url(r'^addstudbatch/$',addstudbatch,name='addstudbatch'),
  url(r'^studbatch/$',viewstuds,name='viewstuds'),

)

from wilp.studbatch.models import StudentBatch
from wilp.faculty.models import Faculty
from wilp.seeker.plugins.model import ModelSearchPlugin



urlpatterns+= patterns('',
    ( r'^search/', include('wilp.seeker.urls'), params ),

)

faculty/models.py
from django.db import models
from wilp.company.models import Company
from wilp.programme.models import Programme
from wilp.courses.models import Course
from wilp.semester.models import Semester
from wilp.coordinator.models import BitsCoordinator
from smart_selects.db_fields import ChainedForeignKey
# Create your models here.

class Faculty(models.Model):
  fac_name = models.CharField(max_length = 100, verbose_name = 'Faculty Name')
  email = models.EmailField()
  phone = models.CharField(max_length = 40)
  mobile = models.CharField(max_length = 40)
  pan_no = models.CharField(max_length = 40, blank = True, null = True)
  gender = models.CharField(max_length = 1000, choices = (('male','Male'),('female','Female')))
  highest_degree = models.CharField(max_length = 1000, blank = True, null = True)
  expertise_area = models.CharField(max_length = 1000, blank = True, null = True)
  indus_exp = models.CharField( max_length = 1000,verbose_name = 'Years of Industry experience', blank = True, null = True)
  teach_exp = models.CharField( max_length = 1000,verbose_name = 'Years of Teaching experience', blank = True, null = True)
  curr_aff = models.CharField(max_length = 1000,verbose_name = 'Current Affilation (Designation & Organisation)', blank = True, null = True)
  hrs = models.CharField(max_length = 1000,verbose_name = 'No of hours expected', blank = True, null = True)
  bank_acc = models.CharField(max_length = 1000, verbose_name = 'Bank account number', blank = True, null = True)
  dd = models.CharField( max_length = 1000, verbose_name = 'DD payable at')
  author = models.ForeignKey(BitsCoordinator,null=True,blank=True)
  
  
  def __unicode__(self):
    return str(self.fac_name)


class FacultySem(models.Model):
  faculty = models.ForeignKey(Faculty)
  company = models.ForeignKey(Company)
  programme = models.ForeignKey(Programme)
  semester = models.ForeignKey(Semester)
  course = models.ForeignKey(Course)
  batch_no = models.CharField(max_length = 40)
  section_no = models.CharField(max_length = 40)
  no_of_students = models.CharField(max_length = 40)
  hrs_expected = models.CharField(max_length = 40,verbose_name = 'No of hours expected to be handled', blank = True, null = True)
  honorarium = models.CharField(max_length = 40,verbose_name = 'Honorarium amount to be paid', blank = True, null = True)
  honorarium_final = models.CharField(max_length = 40,verbose_name = 'Final honorarium amount' , blank = True, null = True)

  def __unicode__(self):
    return str(self.faculty) + " - " + str(self.company) + " - " + str(self.programme)

reports/models.py
from django.db import models

# Create your models here.

studbatch/models.py
from django.db import models
from wilp.company.models import Company
from wilp.programme.models import Programme
from wilp.semester.models import Semester
from smart_selects.db_fields import ChainedForeignKey 
# Create your models here.

class StudentBatch(models.Model):
  company = models.ForeignKey(Company)
  programme = models.ForeignKey(Programme)
  semester = models.ForeignKey(Semester)
  batch = models.ForeignKey('BatchYear')
  sem = models.ForeignKey('Sem')
  males = models.IntegerField(verbose_name = 'No of males Onrolls')
  females = models.IntegerField(verbose_name = 'No of females Onrolls')
  reg_male = models.IntegerField(verbose_name = 'No of males registered')
  reg_female = models.IntegerField(verbose_name = 'No of females registered')
  
  def __unicode__(self):
    return str(self.programme) + ' - '+ str(self.batch) + ' '+str(self.sem) + ' semester' 
  
   
  
class BatchYear(models.Model):
  batch_year = models.IntegerField()
  
  def __unicode__(self):
    return str(self.batch_year)

 
  
class Sem(models.Model):
  sem = models.CharField(max_length = 100, verbose_name = 'Semester')
  
  def __unicode__(self):
    return self.sem
  
 

studbatch/forms.py
from django import forms
from wilp.studbatch.models import StudentBatch

class StudbatchForm(forms.ModelForm):
  def __init__(self, *args, **kwargs):
    super(StudbatchForm, self).__init__(*args, **kwargs)
    for field in self.fields:
      self.fields[field].widget.attrs['class'] = 'text'
  class Meta:
    model = StudentBatch
  

reports/views.py
# Create your views here.
from django.shortcuts import render_to_response
from django.template.loader import render_to_string
from django.http import HttpResponseRedirect,Http404,HttpResponse
from django.utils import simplejson
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django.template import RequestContext
from django.core.exceptions import ObjectDoesNotExist
from wilp.company.models import Company
from wilp.programme.models import Programme

def basic(request):
  companies = Company.objects.all()
  progs = Programme.objects.all()
  return render_to_response('report_base.html',{'progs' : progs, 'companies':companies },context_instance=RequestContext(request))



  

studbatch/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect,Http404,HttpResponse
from django.views.decorators.csrf import csrf_protect
from django.core.urlresolvers import reverse
from django.template import RequestContext
from wilp.studbatch.models import StudentBatch
from wilp.studbatch.forms import StudbatchForm
from wilp.company.models import Company
from wilp.semester.models import Semester

@login_required
@csrf_protect
def addstudbatch(request):
  form = StudbatchForm()
  coms =  Company.objects.filter(coordmanaged__coord__id = request.user.id)
  form.fields["company"].queryset = coms
  form.fields["semester"].queryset = Semester.objects.filter(current=True)
  studs = StudentBatch.objects.filter(company__in = coms)
  if request.POST:
    form = StudbatchForm(request.POST)
    if form.is_valid():
      form.save()
      message = 'Student Batch has been saved'
      form.fields["company"].queryset = Company.objects.filter(coordmanaged__coord__id = request.user.id)
      form.fields["semester"].queryset = Semester.objects.filter(current=True)
      return render_to_response('studbatch.html',{'form':form,'message':message,'studs':studs},context_instance=RequestContext(request))
    else:
      message = 'Please fix the errors below'
      form.fields["company"].queryset = Company.objects.filter(coordmanaged__coord__id = request.user.id)
      form.fields["semester"].queryset = Semester.objects.filter(current=True)
      return render_to_response('studbatch.html',{'form':form,'message':message,'studs':studs},context_instance=RequestContext(request))
  return render_to_response('studbatch.html',{'form':form,'studs':studs},context_instance=RequestContext(request))

@login_required
def viewstuds(request):
  coms =  Company.objects.filter(coordmanaged__coord__id = request.user.id)
  studlist = StudentBatch.objects.filter(company__in = coms)
  print studlist
  return render_to_response('view_studs.html',{'studlist':studlist},context_instance=RequestContext(request))

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
	<title>WILP</title>
	<script type="text/javascript" src="/wilpd/static/js/jquery.js"></script>
	<script type="text/javascript" src="/wilpd/static/js/menu.js"></script>
  <script type="text/javascript" src="/wilpd/static/js/wilp.js"></script>
  <script type="text/javascript">
  {% block script %}

  {% endblock %}
</script>
	<link rel="stylesheet" href="/wilpd/static/css/main.css" type="text/css" />
  {% block extralinks %}
  {% endblock %}
</head>
<body>
	<div id="bg">
		<div class="wrap">

			<!-- logo -->
			<h1><a href="{% url home %}">WILPD</a></h1>
			<!-- /logo -->

			<!-- menu -->
			<div id="mainmenu">
        {% if user.is_authenticated %}
          <span style="color: yellow;position: absolute;margin-top: 5px;margin-left: -450px;font-weight: bold;"> | &nbsp;&nbsp;&nbsp;Welcome , {% if user.get_full_name %}{{ user.get_full_name }}{% else %}{{ user.username }}{% endif %}</span>
        {% endif %}
				<ul id="menu">
					<li><a href="/">Home</a></li>
					{% if user.is_authenticated %}
            <li><a href="{% url logout %}">Logout</a></li>
            <li><a href="">Change Password</a></li>
          {% endif %}
					<li><a href="">Instructions</a></li>
				</ul>
			</div>
			<!-- /menu -->

			<!-- pitch -->
			<div id="pitch" style="height: 50px">

			</div>
			<!-- /pitch -->
      <div id='content'>
			<!-- main -->
			<div id="main" style="min-height: 300px">
      {% if message %}
      <div id='message'>{{ message }}</div>
      <br>
        {% endif %}
        {% block main %}
     {% endblock %}
			</div>
			<!-- /main -->

			<!-- side -->
      {% if user.is_authenticated %}
			<div id="side">
				<h4>Navigation</h4>

				<ul class="side-menu">
					<li><a href="{% url profile %}">My Details</a></li>
					<li><a href="{% url advcompanies %}">Companies</a></li>
					<li><a href="{% url viewcomcoords %}">Company Coordinators</a></li>
					<li><a href="{% url viewfacs %}">Faculty</a></li>
					<li><a href="{% url viewstuds %}">Student Batches</a></li>
				</ul>

			</div>
      {% endif %}
			<!-- /side -->
		</div>
    <!-- /content -->
    </div>
		<!-- footer -->
		<div id="footer">
			<div id="footerbg">
				<div class="wrap">

					<!-- footer links -->
					<p id="footer_menu">
						

						<!-- credit link -->
						
					</p>
					<!-- /footer links -->

					<p id="copy">WILPD <span></span></p>

					<div class="clear"></div>
				</div>
			</div>
		</div>
		<!-- /footer -->

	</div>
</body>
</html>

templates/companies.html
{% extends 'base.html' %}
{% block extralinks %}
<link type="text/css" rel="stylesheet" href="/wilpd/static/css/jquery-ui.css" />
 <script type="text/javascript" src="/wilpd/static/js/jquery-ui.min.js"></script>
  <script type="text/javascript" src="/wilpd/static/js/jquery.scrollTo-min.js"></script>
  <script type="text/javascript" src="/wilpd/static/js/ui.multiselect.js"></script>
  <link rel="stylesheet" href="/wilpd/static/css/ui.multiselect.css" type="text/css" />
{% endblock %}

{% block script %}

$(function(){
  // choose either the full version
  $(".multiselect").multiselect();
  // or disable some features
  
});
{% endblock %}
{% block main %}
   {% if form %}
    <h2 class="inner">Add Companies</h2>
    <form action='' method='post'>
    {% csrf_token %}
      {{ form }}
      <br>
    <span><input type="submit"class="submit" value="Submit"></span>
    </form>
  {% endif %}
  <br><br><br><br>
  <h2 class="inner">Companies Managed</h2>
    {% for comp in companies %}
            {% for company in comp.companies.all %}
               {% if forloop.first %}
              <h3>{{ comp.semester }}</h3>
                <table class='table'>
                <thead><tr><td>Company name</td><td>Place</td></tr></thead>
                <tr class="{% cycle '' 'odd' %}"><td>{{ company.name }}</td><td>{{ company.place }}</td></tr>
                {% else %}
                <tr class="{% cycle 'odd' '' %}"><td>{{ company.name }}</td><td>{{ company.place }}</td></tr>
              {% endif %}
              {% endfor %}
        </table>
    {% endfor %}
   





{% endblock %}

templates/company_coord.html
{% extends 'base.html' %}
{% block main %}
 {% if form %}
  <form action="" method="post">
  {% csrf_token %}
    <h2 class="inner">Add Company Coordinator</h2>
    <table id='profiletable'>
    {% for field in form %}
      <tr><td class="infotag">{{ field.label }}</td><td class='info'>{{ field }}</td><td class='error'>{{ field.errors }}</td></tr>
    {% endfor %}
      <tr><td></td><td><input type="submit"class="submit" value="Submit"></td></tr>
    </table>
  </form>
 {% endif %}
{% endblock %}

templates/coordview.html
{% extends 'base.html' %}
{% block main %}
  <div style="position: absolute;margin-left: 600px;margin-top: 10px"><a href="{% url companycoord %}" class="submit">Add Coordinator</a></div>
  <h2 class="inner">Company Coordinators</h2>
    {% for comc in comcs %}
                 {% if forloop.first %}
                  <table class='table'>
                  <thead><tr><td>Company</td><td>Name</td><td>Address</td><td>Semester</td><td>Phone/Mobile</td><td>Email</td></tr></thead>
                  <tr class="{% cycle '' 'odd' %}"><td>{{ comc.company }}</td><td>{{ comc.name }}</td><td>{{ comc.address }}</td><td>{{ comc.semester.all|first }}</td><td>{{ comc.phone }} / {{ comc.mobile }}</td><td>{{ comc.email }}</td></tr>
                  {% else %}
                  <tr class="{% cycle 'odd' '' %}"><td>{{ comc.company }}</td><td>{{ comc.name }}</td><td>{{ comc.address }}</td><td>{{ comc.semester.all|first }}</td><td>{{ comc.phone }} / {{ comc.mobile }}</td><td>{{ comc.email }}</td></tr>
                {% endif %}
    {% endfor %}
   </table>

{% endblock %}

templates/editprofile.html
{% extends 'base.html' %}
{% block main %}
  {% if message %}
    <div id='message'>{{ message }}</div>
  {% endif %}
  <form action="{% url editprofile %}" method="post">
  {% csrf_token %}
  <table id='profiletable' cellpadding="10px" cellspacing="20px">
  {% for field in form %}
   <tr><td class="infotag">{{ field.label }}</td><td class='info'>{{ field }}</td></tr>
  {% endfor %}
  <tr><td></td><td><input type="submit"class="submit" value="Submit"></td></tr>

  </table>

  </form>
{% endblock %}

templates/fac_add.html
{% extends 'base.html' %}
{% block script %}
  
  function generate_options(values)
{
  var options = '<option selected="selected" value="">---------</option>';
  for(i=0;i<values.length;i++)
  {
    options+='<option value="'+values[i][0]+'">'+values[i][1]+'</option>';
  }

  return options;
}

function filterprogramme(company)
{

  $.get(baseurl+'get_progs/',{'company':company },function(progs){
   $("#id_programme").html(generate_options(progs));
  });
}

function filtercourses(programme)
{

  $.get(baseurl+'get_courses/',{'programme':programme },function(courses){
   $("#id_course").html(generate_options(courses));
  });
}

function binds()
{

  $('#id_company').change(function(){
    filterprogramme($(this).val());
  });

   $('#id_programme').change(function(){
    filtercourses($(this).val());
  });
}


$(document).ready(function(){binds();});
{% endblock %}
{% block main %}
  <h2 class='inner'>Add Faculty</h2>

  {% if sform %}
   <p>Fill in the details below along with the PAN number, if faculty with entered PAN number already exists it will be filled in automatically</p>
  <form action="{% url addfaculty %}" method="post" id='facform'>
    {% csrf_token %}
    <table id='profiletable' cellpadding="10px" cellspacing="20px">
    {% for field in sform %}
      <tr><td class="infotag">{{ field.label }}</td><td class='info'>{{ field }}</td></tr>
    {% endfor %}
    <tr><td></td><td><input type="submit"class="submit" value="Submit" name='submit1'></td></tr>
    </table>
  {% else %}

   {% if fform %}
    {% endif %}
  {% if sform2 %}
     <h3 class="inner">Course details</h3>
    <hr>
    <form action="{% url addfaculty %}" method="post" id='facform'>
    {% csrf_token %}
    <table id='profiletable' cellpadding="10px" cellspacing="20px">
    {% for field in sform2 %}
      <tr><td class="infotag">{{ field.label }}</td><td class='info'>{{ field }}</td><td>{{ field.errors }}</td></tr>
    {% endfor %}
    </table>
  {% endif %}

  {% if fform %}
    <h3 class="inner">Personal details</h3>
    <hr>
    <table id='profiletable' cellpadding="10px" cellspacing="20px">
    {% for field in fform %}
      <tr><td class="infotag">{{ field.label }}</td><td class='info'>{{ field }}</td><td>{{ field.errors }}</td></tr>
    {% endfor %}
      <tr><td></td><td><input type="submit"class="submit" value="Submit" name='submit2'></td></tr>
    </table>
  </form>
  {% endif %}
{% endif %}

{% endblock %}

templates/faculty_report.html
<html>
<head>
<style type="text/css">

 body
 {
   font-family: arial;
 }
.row1
{
	border-bottom: 1px solid;
	border-bottom-color: #000;
	text-align: center;
  padding-top: 4px;
  padding-bottom:2px;
	
	
}

.row2 
{
	background-color: #dddddd;
	padding-top: 4px;
  padding-bottom:2px;
	border-bottom: 1px solid;
	border-bottom-color: #000;
	text-align: center;
    
}

table
{
  margin-top: 30px;

}

#header
{
  border-bottom: 1px solid;
  border-color: #000;
  border-top: 1px solid;
  text-align: center;
  font-size: 12px;
  font-weight: bold;
  padding-bottom: 5px;
  padding-top: 5px;
}

#total
{
  position: relative;
  margin-top: 30px;
  margin-left: 560px;
  font-size: 12px;
  font-weight: bold;
}
</style>
</head>
<body>

<p>To,</p>
<p>Deputy Director (Off-Campus Programmes)<br /> BITS, Pilani</p>
<p>Date : {{ today|date:"D d M Y" }}</p>
<p>Sir,</p>
<p>Subject : Payment of Honorarium {% if company %}for {{ company }}{% endif %}{% if programme %},{{ programme }}{% endif %}{% if course %},{{ course }}{% endif %}</p>
<p>I seek your approval for the payment of honorarium towards teaching and evaluation of courses conducted by our institute, by demand draft drawn in the name of the person concerned, payable at as per details given below</p>

<table>
<thead ><tr id='header'><td>Faculty Name</td><td>Programme</td><td>Course</td><td>Company</td><td>Honorarium</td></tr></thead>
{% for fac in facs %}
  <tr  class="{% cycle 'row1' 'row2' %}">
    <td> {{ fac.faculty }} </td><td> {{ fac.programme }} </td><td> {{ fac.course }} </td><td>{{ fac.company }}</td><td>{{ fac.honorarium_final }}</td>
  </tr>
{% endfor %}
</table>
<div id="total">Total amount : {{ total }}</div>
<br/>
<p>
Sincerely,<br/><br/><br/><br/>
Assistant Dean,WILP Division.
</p>
</body>
</html>

templates/report_base.html
{% extends 'admin/base_site.html' %}
{% block title %} Faculty Report {% endblock %}
{% block content %}


{% block report_title %} <h1> Faculty Report </h1> {% endblock %}	
 
<form>

	<select name="company">
		{% for company in companies %}
			<option>{{ company }}	</option>
		{% endfor %}	
	</select>
	
	<select name="programme">
		{% for prog in progs %}
			<option>{{ prog }}</option>
		{% endfor %}	
	</select>
	
	

</form>



			

{% endblock %}

templates/report_bitscoord.html
{% extends "admin/base_site.html" %}
{% load adminmedia admin_list i18n %}
{% load url from future %}
{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% admin_media_prefix %}css/changelists.css" />
  {% if cl.formset %}
    <link rel="stylesheet" type="text/css" href="{% admin_media_prefix %}css/forms.css" />
  {% endif %}
  {% if cl.formset or action_form %}
    {% url 'admin:jsi18n' as jsi18nurl %}
    <script type="text/javascript" src="{{ jsi18nurl|default:'../../jsi18n/' }}"></script>
  {% endif %}
  {{ media.css }}
  {% if not actions_on_top and not actions_on_bottom %}
    <style>
      #changelist table thead th:first-child {width: inherit}
    </style>
  {% endif %}
{% endblock %}

{% block extrahead %}
{{ block.super }}
{{ media.js }}
{% if action_form %}{% if actions_on_top or actions_on_bottom %}
<script type="text/javascript">
(function($) {
    $(document).ready(function($) {
        $("tr input.action-select").actions();
    });
})(django.jQuery);
</script>
{% endif %}{% endif %}
{% endblock %}

{% block bodyclass %}change-list{% endblock %}

{% if not is_popup %}
  {% block breadcrumbs %}
    <div class="breadcrumbs">
      <a href="../../">
        {% trans "Home" %}
      </a>
       &rsaquo;
       <a href="../">
         {{ app_label|capfirst }}
      </a>
      &rsaquo;
      BITS Coordinator Report
    </div>
  {% endblock %}
{% endif %}

{% block coltype %}flex{% endblock %}
{% block content_title %}<h1>BITS Coordinator Report</h1> {% endblock %}
{% block content %}
  <div id="content-main">
    {% block object-tools %}
      {% if has_add_permission %}
        <ul class="object-tools">
          {% block object-tools-items %}
            
          {% endblock %}
        </ul>
      {% endif %}
    {% endblock %}
    {% if cl.formset.errors %}
        <p class="errornote">
        {% blocktrans count cl.formset.errors|length as counter %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktrans %}
        </p>
        {{ cl.formset.non_form_errors }}
    {% endif %}
    <div class="module{% if cl.has_filters %} filtered{% endif %}" id="changelist">
      {% block search %}{% search_form cl %}{% endblock %}
      {% block date_hierarchy %}{% date_hierarchy cl %}{% endblock %}

      {% block filters %}
        {% if cl.has_filters %}
          <div id="changelist-filter">
            <h2>{% trans 'Filter' %}</h2>
            {% for spec in cl.filter_specs %}{% admin_list_filter cl spec %}{% endfor %}
          </div>
        {% endif %}
      {% endblock %}

      <form id="changelist-form" action="" method="post"{% if cl.formset.is_multipart %} enctype="multipart/form-data"{% endif %}>{% csrf_token %}
      {% if cl.formset %}
        <div>{{ cl.formset.management_form }}</div>
      {% endif %}

      {% block result_list %}
          {% if action_form and actions_on_top and cl.full_result_count %}{% admin_actions %}{% endif %}
          {% result_list cl %}
          {% if action_form and actions_on_bottom and cl.full_result_count %}{% admin_actions %}{% endif %}
      {% endblock %}
      {% block pagination %}{% pagination cl %}{% endblock %}
      </form>
    </div>
  </div>
{% endblock %}

templates/reports.html
{% extends 'admin/base_site.html' %}

{% block title %}Reports{% endblock %}


{% block breadcrumbs %}
<div class="breadcrumbs">

<a href="/admin/">Home</a> &rsaquo;
<a href="{% url reports %}">Reports</a>
</div>
{% endblock %}
{% block content %}
  <h1>View Reports</h1>
  <div id="settings_form" style="padding:40px;">
  <style type="text/css">
      #settings_form li
      {
        font-size: 14px;
        padding: 10px;
        font-weight: bold;
      }
  </style>

  <ul>
    <li><a href="/admin/faculty/facultysem/">Faculty Report</a></li>
    <li><a href="/admin/coordinator/companycoordinator/">Company Coordinator</a></li>
    <li><a href="/admin/coordinator/coordmanaged/">Companies managed by BITS Coordinator</a></li>
    <li><a href="/admin/studbatch/studentbatch/">Student details</a></li>
    <li><a href="/admin/programme/prorammesem/">Programme wise companies</a></li>
  </ul>
  </div>
{% endblock %}

templates/search.html
{% extends "base.html" %}

{% block extralinks %}
<link rel="stylesheet" type="text/css" href="/wilpd/static/css/seeker.css" />
<link rel="stylesheet" type="text/css" href="/wilpd/static/css/ui.datepicker.css" />
<script type="text/javascript" src="/wilpd/static/js/json2.js"></script>
<script type="text/javascript" src="/wilpd/static/js/jquery.form.js"></script>
<script type="text/javascript" src="/wilpd/static/js/ui.datepicker.js"></script>
<script type="text/javascript" src="/wilpd/static/js/seeker.util.js"></script>
<script type="text/javascript" src="/wilpd/static/js/seeker.filter.js"></script>
<script type="text/javascript" src="/wilpd/static/js/seeker.results.js"></script>
<script type="text/javascript" src="/wilpd/static/js/seeker.init.js"></script>
{% endblock %}

{% block main %}

{% block seeker %}
{% endblock %}

{% endblock %}

templates/settings.html
{% extends 'admin/base_site.html' %}

{% block title %}BITS Coordinator Settings{% endblock %}


{% block breadcrumbs %}
<div class="breadcrumbs">

<a href="/">Home</a> &rsaquo; 
<a href="{% url settings %}">Settings</a>
</div>
{% endblock %}

{% block content %}


<h1>BITS Coordinator Settings</h1>



<div id="settings_form" style="padding:40px;">
<form action="{% url settings %}" method="post">
{% csrf_token %}
    {% for field in form %}
        <div class="fieldWrapper" style="padding:10px;">
            {{ field.errors }}
             {{ field }} {{ field.label_tag }}
             <p class="help">{{ field.help_text }} </p>
        </div>
    {% endfor %}
    <p><input type="submit" style="margin-top:20px;margin-left:40px;width:150px;height:30px;" value="Save settings"/></p>
</form>
</div>


			

{% endblock %}